### ISSUE TITLE
KVM: backend: the third level indent in 'User Data' is missing when decoding metadata.

### ISSUE THREAD

**Issue by xieqiang2020** [IBM/cloudland#237]
When creating a new instance, base64 encodes the 'User Data' to metadata and sends the metadata to backend. The backend, for example, the kvm/launch_vm.sh, will decode the metadata and use the 'User Data' in cloud-init configuration. However, it seems that the third level indent is missing, which fails the cloud-init configuration.

Original:
```#cloud-config
yum_repos:
    rhel78:
        baseurl: http://xxx.xxx.xxx.xxx/mirrors/mounted/rhel78
        enabled: true
        name: rhel78
        gpgcheck: false
```
Parsed:
```
#cloud-config
yum_repos:
    rhel78:
    baseurl: http://xxx.xxx.xxx.xxx/mirrors/mounted/rhel78
    enabled: true
    name: rhel78
    gpgcheck: false
```
